// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfiuZSZhbSBu6C7u64iDLG821nYOrhEdI',
    appId: '1:76274177509:web:6d57ab750994e100b08b0c',
    messagingSenderId: '76274177509',
    projectId: 'routineup-a17c7',
    authDomain: 'routineup-a17c7.firebaseapp.com',
    storageBucket: 'routineup-a17c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNvAUR1xCFVKkdN2nBpcDNuXpeJzZFhhM',
    appId: '1:76274177509:android:b7b346075b2f1157b08b0c',
    messagingSenderId: '76274177509',
    projectId: 'routineup-a17c7',
    storageBucket: 'routineup-a17c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXek4I_8uy-VtwJSFesWuEJQ9R9tGB_eg',
    appId: '1:76274177509:ios:cf02c6427b47bafdb08b0c',
    messagingSenderId: '76274177509',
    projectId: 'routineup-a17c7',
    storageBucket: 'routineup-a17c7.firebasestorage.app',
    iosBundleId: 'com.example.routineup',
  );
}
